In [1]:
import numpy as np

creating a matrix using numpy

In [6]:
matrix_1=np.array([[2,3],[6,7],[7,9]])
print(matrix_1)

[[2 3]
 [6 7]
 [7 9]]


In [7]:
#find the shape of matrix
matrix_1.shape

(3, 2)

creating matrices with random values

In [11]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.54541845 0.67893385 0.92481834]
 [0.01493962 0.74468148 0.76928383]
 [0.22653192 0.45754562 0.04588798]]


In [12]:
random_matrix1=np.random.randint(100,size=(4,5))
print(random_matrix1)

[[61 86 27 23 70]
 [78 79 50 65 20]
 [85 40 22 59 67]
 [27 97  6 33 16]]


matrix with all avlues as 1

In [15]:
matrix_3=np.ones((3,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


null matrix or zero matrix

In [17]:
zero_matrix=np.zeros((4,5),dtype=int)
print(zero_matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Identity matrix

In [20]:
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


transpose

In [21]:
a=np.random.randint(100,size=(4,5))
print(a)

[[26 19 93  9 75]
 [44 24 75 24 93]
 [53 81 64 28 53]
 [20  4 12 88 83]]


In [22]:
transpose_of_a=np.transpose(a)
print(transpose_of_a)

[[26 44 53 20]
 [19 24 81  4]
 [93 75 64 12]
 [ 9 24 28 88]
 [75 93 53 83]]


matrix operations

matrix addition

In [24]:
vector_1=np.array([[1,2],[4,5]])
vector_2=np.array([[6,7],[8,9]])
sum=vector_1 + vector_2
print(sum)

[[ 7  9]
 [12 14]]


In [33]:
vector_1=np.array([[1,2],[4,5]])
vector_2=np.array([[6,7],[8,9]])
c=np.add(vector_1,vector_2)
print(c)

[[ 7  9]
 [12 14]]


In [26]:
a=np.random.randint(100,size=(3,4))
print(a)
b=np.random.randint(150,size=(3,4))
print(b)
c=a+b
print(c)

[[27  2  4 85]
 [86 56 64 10]
 [35 23 90  2]]
[[127  75  78 137]
 [ 30  69  13  49]
 [ 94  25  83 127]]
[[154  77  82 222]
 [116 125  77  59]
 [129  48 173 129]]


In [34]:
a=np.random.randint(100,size=(3,4))
print(a)
b=np.random.randint(150,size=(3,4))
print(b)
c=np.add(a,b)
print(c)

[[17 24 23 67]
 [81 95 37 19]
 [42 43 42 71]]
[[ 62 113  27  49]
 [ 13  76 119  28]
 [117  87 129  82]]
[[ 79 137  50 116]
 [ 94 171 156  47]
 [159 130 171 153]]


matrix subtraction

In [27]:
vector_1=np.array([[1,2],[4,5]])
vector_2=np.array([[6,7],[8,9]])
diff=vector_1 - vector_2
print(diff)

[[-5 -5]
 [-4 -4]]


In [35]:
vector_1=np.array([[1,2],[4,5]])
vector_2=np.array([[6,7],[8,9]])
diff=np.subtract(vector_1,vector_2)
print(diff)

[[-5 -5]
 [-4 -4]]


In [28]:
a=np.random.randint(100,size=(3,4))
print(a)
b=np.random.randint(150,size=(3,4))
print(b)
c=b-a
print(c)

[[68 45 11 46]
 [53 20 79 18]
 [ 2 87 30 91]]
[[135 107  48 126]
 [128 101  32   1]
 [120  97  55 127]]
[[ 67  62  37  80]
 [ 75  81 -47 -17]
 [118  10  25  36]]


In [37]:
a=np.random.randint(100,size=(3,4))
print(a)
b=np.random.randint(150,size=(3,4))
print(b)
c=np.subtract(b,a)
print(c)

[[20 46 64 73]
 [75 74 74 23]
 [89 15 71 76]]
[[ 42 146  44  53]
 [ 20  68  74  30]
 [  3  52 108 116]]
[[ 22 100 -20 -20]
 [-55  -6   0   7]
 [-86  37  37  40]]


multiplying a matrix with scalar

In [29]:
vector_1=np.array([[1,2],[4,5]])
vector_2= 2*vector_1
print(vector_2)

[[ 2  4]
 [ 8 10]]


In [39]:
vector_1=np.array([[1,2],[4,5]])
x=2
product=np.multiply(x,vector_1)
print(product)

[[ 2  4]
 [ 8 10]]


In [31]:
a=np.random.randint(10,size=(3,4))
print(a)
b=2*a
print(b)

[[1 1 6 2]
 [5 9 7 0]
 [1 5 8 0]]
[[ 2  2 12  4]
 [10 18 14  0]
 [ 2 10 16  0]]


In [40]:
a=np.random.randint(10,size=(3,4))
print(a)
b=2
c=np.multiply(a,b)
print(c)

[[9 4 9 2]
 [4 6 8 3]
 [1 7 9 6]]
[[18  8 18  4]
 [ 8 12 16  6]
 [ 2 14 18 12]]


multiplying matrices

In [42]:
vector_1=np.array([[1,2],[4,5]])
vector_2=np.array([[6,7],[8,9]])
product=np.dot(vector_1,vector_2)
print(product)
print(product.shape)

[[22 25]
 [64 73]]
(2, 2)


In [45]:
a=np.random.randint(5,size=(3,4))
print(a)
b=np.random.randint(5,size=(4,5))
print(b)
c=np.dot(a,b)
print(c)
print(c.shape)

[[3 1 1 3]
 [3 0 0 1]
 [3 2 3 0]]
[[4 4 3 4 4]
 [0 1 4 0 2]
 [2 4 1 1 1]
 [1 0 4 1 3]]
[[17 17 26 16 24]
 [13 12 13 13 15]
 [18 26 20 15 19]]
(3, 5)


element ise multiplication

In [49]:
a=np.random.randint(5,size=(3,4))
print(a)
b=np.random.randint(5,size=(3,4))
print(b)
c=np.multiply(a,b)
print(c)

[[2 0 1 0]
 [1 2 2 0]
 [1 3 0 4]]
[[0 3 0 2]
 [2 2 2 2]
 [0 3 1 3]]
[[ 0  0  0  0]
 [ 2  4  4  0]
 [ 0  9  0 12]]
