Numpy --Numerial Python

adavantages:
1.allows several mathematial operations

2.faster operations

In [1]:
import numpy as np

list vs numpy --time taken

In [2]:
from time import process_time

time taken by a list

In [3]:
python_list=[i for i in range(10000)]
start_time=process_time()

python_list = [i+5 for i in python_list]

end_time=process_time()
print(end_time-start_time)

0.0009241089999996177


In [4]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0005852349999990736


numpy Arrays

In [6]:
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [7]:
np_array=np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#creating one dimensional array
a=np.array([2,3,4])
print(a)

[2 3 4]


In [9]:
a.shape

(3,)

In [15]:
b=np.array([(1,2,3),(4,5,6)])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [17]:
c=np.array([(1,2,3),(4,5,6)],dtype=float)
print(c)
print(type(c))
c.shape

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>


(2, 3)

intial placeholders

In [19]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
y=np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
z=np.full((5,4),24)
print(z)

[[24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]]


In [25]:
p=np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
#create numpy with random values
q=np.random.random((3,4))
print(q)

[[0.48203233 0.60984089 0.2536287  0.55966223]
 [0.13403986 0.3257416  0.03716571 0.27180706]
 [0.87340615 0.1800104  0.46137056 0.08517332]]


In [29]:
#random integer values array withim specific range
c=np.random.randint(10,100,(3,4))
print(c)

[[92 19 46 77]
 [69 58 54 64]
 [49 79 18 15]]


In [36]:
# array of evenly spaced values
t=np.linspace(10,30,7)
print(t)

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.        ]


In [35]:
#array of evenly spaces
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [37]:
#convert a list into np array
list1=[10,20,30,40,50]
np_array=np.asarray(list1)
print(np_array)
print(type(np_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


analyze a np array

In [38]:
c=np.random.randint(10,90,(5,5))
print(c)

[[58 79 60 60 84]
 [88 87 67 13 32]
 [47 75 88 38 18]
 [38 39 30 33 50]
 [84 22 68 87 45]]


In [39]:
#array dimension
c.shape

(5, 5)

In [40]:
#num of dimensions
print(c.ndim)

2


In [41]:
#no.of elements in array
print(c.size)

25


In [42]:
#checking the data type of values in array
print(c.dtype)

int64


mathematical operations

In [43]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [44]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)

[[8 5 5]
 [7 3 9]
 [4 1 3]]
[[17 16 19]
 [13 11 13]
 [18 14 14]]
[[25 21 24]
 [20 14 22]
 [22 15 17]]


In [45]:
print(a+b)

[[25 21 24]
 [20 14 22]
 [22 15 17]]


In [48]:
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)

[[ -9 -11 -14]
 [ -6  -8  -4]
 [-14 -13 -11]]
[[136  80  95]
 [ 91  33 117]
 [ 72  14  42]]
[[0.47058824 0.3125     0.26315789]
 [0.53846154 0.27272727 0.69230769]
 [0.22222222 0.07142857 0.21428571]]
[[2251799813685248     152587890625   19073486328125]
 [     96889010407           177147    2541865828329]
 [     68719476736                1          4782969]]
[[8 5 5]
 [7 3 9]
 [4 1 3]]


In [49]:
print(np.add(a,b))

[[25 21 24]
 [20 14 22]
 [22 15 17]]


In [50]:
p=np.random.randint(20,40,(4,4))
q=np.random.randint(30,40,(4,4))
print(p)
print(q)

[[25 37 32 26]
 [20 31 29 28]
 [23 32 33 38]
 [31 30 32 32]]
[[33 36 35 34]
 [31 30 36 32]
 [30 34 36 33]
 [36 37 34 30]]


In [51]:
print(p+q)
print(p-q)
print(p*q)
print(p/q)
print(p//q)
print(p**q)
print(p%q)

[[58 73 67 60]
 [51 61 65 60]
 [53 66 69 71]
 [67 67 66 62]]
[[ -8   1  -3  -8]
 [-11   1  -7  -4]
 [ -7  -2  -3   5]
 [ -5  -7  -2   2]]
[[ 825 1332 1120  884]
 [ 620  930 1044  896]
 [ 690 1088 1188 1254]
 [1116 1110 1088  960]]
[[0.75757576 1.02777778 0.91428571 0.76470588]
 [0.64516129 1.03333333 0.80555556 0.875     ]
 [0.76666667 0.94117647 0.91666667 1.15151515]
 [0.86111111 0.81081081 0.94117647 1.06666667]]
[[0 1 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]]
[[-4355210815010437351  4360306654246978673                    0
   5566929230874279936]
 [ 4611686018427387904  8776101465919375425  4369643239592306001
                     0]
 [   20724412416931825                    0 -3475390556911444863
  -3363437791995232256]
 [ -647720439872236671  7980670872354553856                    0
                     0]]
[[25  1 32 26]
 [20  1 29 28]
 [23 32 33  5]
 [31 30 32  2]]


In [52]:
print(np.add(p,q))

[[58 73 67 60]
 [51 61 65 60]
 [53 66 69 71]
 [67 67 66 62]]


In [53]:
print(np.subtract(p,q))

[[ -8   1  -3  -8]
 [-11   1  -7  -4]
 [ -7  -2  -3   5]
 [ -5  -7  -2   2]]


In [54]:
print(np.multiply(p,q))
print(np.divide(p,q))

[[ 825 1332 1120  884]
 [ 620  930 1044  896]
 [ 690 1088 1188 1254]
 [1116 1110 1088  960]]
[[0.75757576 1.02777778 0.91428571 0.76470588]
 [0.64516129 1.03333333 0.80555556 0.875     ]
 [0.76666667 0.94117647 0.91666667 1.15151515]
 [0.86111111 0.81081081 0.94117647 1.06666667]]


In [56]:
print(np.floor_divide(p,q))

[[0 1 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]]


In [59]:
print(np.absolute(p,q))

[[25 37 32 26]
 [20 31 29 28]
 [23 32 33 38]
 [31 30 32 32]]


array manipulation

In [62]:
array=np.random.randint(0,10,(2,4))
print(array)
print(array.shape)

[[4 1 4 3]
 [0 1 5 1]]
(2, 4)


In [63]:
#transpose
trans=np.transpose(array)
print(trans)

[[4 0]
 [1 1]
 [4 5]
 [3 1]]


In [64]:
#anthoer metghod for transpose
trans2=array.T
print(trans2)
print(trans2.shape)

[[4 0]
 [1 1]
 [4 5]
 [3 1]]
(4, 2)


In [65]:
#reshaping a array
a=np.random.randint(10,20,(2,4))
print(a)
print(a.shape)

[[15 18 19 10]
 [13 10 13 18]]
(2, 4)


In [68]:
b=a.reshape(4,2)
print(b)

[[15 18]
 [19 10]
 [13 10]
 [13 18]]


In [70]:
c=np.reshape(b,(2,4))
print(c)

[[15 18 19 10]
 [13 10 13 18]]


In [71]:
a=np.random.randint(10,30,(4,5))
print(a)

[[23 13 29 24 22]
 [29 26 29 21 20]
 [14 29 25 10 24]
 [17 16 12 18 13]]
